# Generated by Django 5.0.3 on 2024-03-20 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='class', max_length=50)),
                ('syllabus', models.TextField(blank=True, verbose_name='Syllabus')),
                ('price', models.FloatField(blank=True, default=0, verbose_name='Price')),
                ('class_time', models.TimeField(blank=True)),
                ('meet_link', models.CharField(blank=True, max_length=500, verbose_name='Meet Link')),
                ('teacher', models.ForeignKey(limit_choices_to={'userprofile__role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='ClassroomResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_file', models.FileField(blank=True, upload_to='classroom_resources/')),
                ('message', models.TextField(blank=True)),
                ('class_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_resources', to='tution.classmodel')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classroom Resource',
                'verbose_name_plural': 'Classroom Resources',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('student', 'Student'), ('super admin', 'Super Admin')], default='', max_length=12, verbose_name='role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cannot_attended', 'Cannot Attended'), ('can_attend', 'Can Attend')], default='cannot_attended', max_length=20)),
                ('class_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='tution.classmodel')),
                ('student', models.ForeignKey(limit_choices_to={'userprofile__role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'class_enrolled')},
            },
        ),
    ]
