# Generated by Django 5.0.3 on 2024-03-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='class_time',
            field=models.TimeField(blank=True, default=None),
        ),
    ]
