# Generated by Django 5.0.3 on 2024-03-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0004_classroomresource_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledstudent',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='enrolledstudent',
            name='parent_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='enrolledstudent',
            name='parent_phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='enrolledstudent',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
