# Generated by Django 5.0.3 on 2024-03-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0005_enrolledstudent_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledstudent',
            name='address',
            field=models.CharField(default='', max_length=20),
        ),
    ]
