# Generated by Django 5.0.3 on 2024-03-21 07:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0006_enrolledstudent_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledstudent',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
