# Generated by Django 5.0.3 on 2024-03-22 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0007_enrolledstudent_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_proof', models.FileField(upload_to='payments/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tution.enrolledstudent')),
            ],
        ),
    ]
