# Generated by Django 5.0.3 on 2024-03-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0008_enrollmentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
