# Generated by Django 5.0.3 on 2024-03-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0009_userprofile_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='testimonials/')),
                ('designation', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
